### ISSUE TITLE
Help with Browserify

### ISSUE THREAD

**Issue by ebowers** [fbrctr/fabricator#111]
Hi there,

I contacted you on twitter to see if you could help me out. I am new to Browserify and modular JS in general. I really would love to start using Fabricator and I think I just need an example to get me over the hump. I am trying to hook up [Floating Labels] (https://github.com/datuhealth/floating-label), so I first downloaded installed the [Boilerplate Toolkit] (https://github.com/fbrctr/boilerplate-toolkit) for using 3rd party libraries. Then I used Bower to install the Floating Label script and included it in the gulp file like so...

```javascript
vendor: [
  'bower_components/jquery/dist/jquery.js',
  'bower_components/floatingLabel.js/dist/floatingLabel.js',
  'bower_components/es5-shim.min.js'
],
```

Then I created a js file called form.js and put this inside of it...

```javascript
var $ = require('bower_components/floatingLabel.js/dist/floatingLabel.js');
module.exports = floatingLabel.init();
```

After that, I tried importing it into toolkit.js, that files looks like this...

```javascript
'use strict';

var button = require("./components/button");
var form = require("./components/form");

button.sayHi();
```
and I am not seeing the floating label functionality showing up. I am sure I'm doing something wrong, I'm just not sure what it is.

I really appreciate any help at all, just trying to learn and I think I need a real world example.

Thank you!

**Comment by LukeAskew** [comment]
This is a little different than the approach outlined in the docs, but it is still a valid approach.

Your form.js is probably not working because the path to `floatingLabel.js` isn't resolving. By default, browserify starts resolving paths relative to the current file. It will also try to resolve paths relative to the `node_modules` directory (allowing you to manage third-party deps with npm).

You can probably fix the issue by changing the require statement in form.js to something like:

```javascript
var $ = require('../../../../bower_components/floatingLabel.js/dist/floatingLabel.js');
```

**Comment by LukeAskew** [comment]
FWIW, Browserify will soon [be replaced by Webpack](https://github.com/fbrctr/fabricator/pull/110). It shouldn't affect the way you're including modules, and since you've already started your Fabricator instance, you wouldn't get the update unless you re-scaffolded or pulled in the change manually.

**Comment by ebowers** [comment]
Great. Thanks @LukeAskew !
