### ISSUE TITLE
CSS not loading for pages

### ISSUE THREAD

**Issue by astanush** [fbrctr/fabricator#112]
I made a change to my `src/toolkit/styles/toolkit.scss`, but noticed the styles weren't being applied to `/pages/home.html`.

I added a leading `/` to the CSS path `assets/toolkit/styles/toolkit.css` in Chrome inspector and that seemed to fix the issue.

https://github.com/fbrctr/fabricator/blob/430327391bdc7b25c60627408bfc0c633eaf8b0a/src/views/layouts/default.html#L13

**Comment by LukeAskew** [comment]
That's a bug from the recent overhaul. All pages used to save out to a single directory, but now they can be in sub-directories. Adding the `{{baseurl}}` var helps resolve paths.

Thanks for logging this.

**Comment by dietergeerts** [comment]
This doesn't work if the toolkit is in a subfolder of your server...

**Comment by mandalatv** [comment]
I'd hate to have to put ./ before every instance of {{baseurl}}... 
Where's a good place to define baseurl for all template files to inherit it?

**Comment by LukeAskew** [comment]
`baseurl` is an internal var right now, and is not configurable. You could store your own value in a data file under `src/data` and use it the same way (as a path prefix).
