### ISSUE TITLE
material front-matter data doesn't work

### ISSUE THREAD

**Issue by LukeAskew** [fbrctr/fabricator#116]
Per the [docs](http://fbrctr.github.io/building-a-toolkit/data.html), you should be able to define data in a material's front-matter. e.g.:

```html
---
bar: "spam"
---
<div>foo {{bar}}</div>
```

Expected:
```html
<div>foo spam</div>
```

Actual:
```html
<div>foo </div>
```

h/t @casio for bringing this up in the Gitter channel

**Comment by LukeAskew** [comment]
This should be fixed by https://github.com/fbrctr/fabricator-assemble/commit/01ace9c8b311f66e820d3e6c0f9097fea5212d5e

Looking for some help testing. You can install the pre-release using: 

```
$ npm install --save-dev https://github.com/fbrctr/fabricator-assemble/tarball/master
```

**Comment by casio** [comment]
Nice, that fixes the issue, thx!

Regarding my other question on the gitter channel wrt overriding vars from outer structures, views, etc.
That doesnt seem to work currently. Example:

    // src/materials/components/button.html
    ---
    modifier: "btn-default"
    label: "Submit"
    ---
    <button class="btn {{modifier}}">{{label}} - {{externalvar}}</button>
    
    // src/materials/components/allbuttons.html
    {{> button label="OK" }}
    {{> button label="Cancel" modifier="btn-warning" }}
    {{> button label="Buy now" externalvar="Foo some" }}

This will only render "Submit" buttons. However the `externalvar` is being rendered correctly.

Dont know if this is intended behaviour, but I think it'd be great to support this kind of configuration of components from inside structures, view, etc.

**Comment by LukeAskew** [comment]
This is the intended prioritization of context. Compilation happens at the smallest part and moves outward. 

material
:arrow_down: 
parent material(s)
:arrow_down: 
view

The materials (partials) have to be parse first in order to make them available to views.

What are you trying to achieve? Default values?

**Comment by casio** [comment]
> What are you trying to achieve? Default values?

Yea, default values and the abili

**Comment by casio** [comment]
Take the above button example. How'd U deal with such a configurable component in a toolkit?
Have one `.html` file/material per each permutation and use partials like `{{> button-warning }}`?

Probably better to put up another issue for this, I guess..

**Comment by LukeAskew** [comment]
You can group permutations in folders.

```
└── buttons
  ├── primary.html
  ├── secondary.html
  └── tertiary.html
```

```
{{> buttons.primary}}
{{> buttons.secondary}}
```

**Comment by casio** [comment]
Hm, that doesnt scale that much, though. What if `btn-sm` & friends come into play then?
