### ISSUE TITLE
Optional page path setting

### ISSUE THREAD

**Issue by Yago** [fbrctr/fabricator#117]
Hi ! I just start to use Fabricator in my projects and I'm very exited :smile:

I would like to make a suggestion : what do you think about having a optional front-matter path setting in page files ? Something like : 

`````html
---
path : my-awesome-cms/theme/templates/
---
<h1>Hello, World!</h1>

{{> paragraph}}

<div>
	{{> form}}
</div>
````

Then the page will be build in the `dest` and if exist, in the optional template path. With this feature, your project will be the ultimate frontend tool :+1:

**Comment by LukeAskew** [comment]
Interesting. I'll spend some time thinking about how to make that work. I think it could be useful.

**Comment by Yago** [comment]
Hey @LukeAskew some news on this side ?

**Comment by LukeAskew** [comment]
In the middle of a crunch at work. I'll have some time to dedicate to this next week. I think it'll be fairly easy to integrate.

**Comment by Yago** [comment]
Great ! I'm excited to use it :smile:
