### ISSUE TITLE
Atomic Design menu struc

### ISSUE THREAD

**Issue by barrymcgee** [fbrctr/fabricator#124]
I'd like to use an Atomic Design structure as noted in the docs;

```
└── materials
    ├── atoms
    ├── molecules
    └── organism
```

..however, when I build straight out of the box and rename 'Components' to 'Atoms'; the site will build but all links will 404 when linking to atoms.html#partial ?

**Comment by LukeAskew** [comment]
You have to build the "listing" views yourself. 

For example, the default file: `src/views/components.html` contains an `{{#each}}` block that iterates over `materials.components.items`.

You should be able to rename this file to `atoms.html` and change the reference to `materials.atoms.items`.
