### ISSUE TITLE
Include CSS, JS and data files at a material level, exclude from pattern listing

### ISSUE THREAD

**Issue by paulrobertlloyd** [fbrctr/fabricator#125]
This may be a feature request, or a more general question! If I wanted to have all assets (JS, CSS, JSON etc…) relating to a component placed together in the same folder (i.e. within a folder within the materials folder), how might I exclude these supporting assets from being rendered on the output pattern library? Is this simply something that can be achieved in handlebars templates, or does it require fiddling with the output of `items` some other way?

**Comment by LukeAskew** [comment]
The default glob for materials is pretty inclusive `src/materials/**/*`. You should be able to pass a new pattern to the `assemble()` task in the `gulpfile.js`.

Something like this:

```javascript
// assemble
gulp.task('assemble', function (done) {
    assemble({
        materials: 'src/materials/**/*.html',    
    });
    done();
});
```

https://github.com/fbrctr/fabricator-assemble#options

**Comment by paulrobertlloyd** [comment]
Ah ha! That makes a lot of sense actually. Thanks (and closing).

**Comment by jameswragg** [comment]
@paulrobertlloyd we'll probably be following the same approach with our Fabricator toolkit. I'd very much like to see how yours turned out if it's available anywhere?

**Comment by paulrobertlloyd** [comment]
@jameswragg It’s not public, I’m afraid (and by all accounts, the project is going in a different direction now…). Sorry!
