### ISSUE TITLE
Better support for custom order of materials

### ISSUE THREAD

**Issue by slightlyoffbeat** [fbrctr/fabricator#126]
Currently, everything is alphabetical order. You can customize, but you lose some automation. It would be great to be able to name .html files with numbers so that we can have better control over the order in which everything appears (without the numbers showing up in the name).

**Comment by lyzadanger** [comment]
+1 This is the most material change we've had to make to our fork. We've written a Handlebars helper to regexp off prefixed ordering patterns from names for display, but it feels less than elegant. Thanks!

**Comment by LukeAskew** [comment]
:+1: 

This is a request I've heard a lot, so it's probably time to make it happen.

Can you provide some examples of how you're naming files? I'd like to see some real-word usage to help come up with a good solution.

**Comment by lyzadanger** [comment]
@LukeAskew Sure! We originally picked up the naming convention we're using from [Pattern Lab](http://patternlab.io/docs/pattern-reorganizing.html), that is, prefixing filenames with digits and a hyphen. I don't think we're attached to the specifics, but it's nice to be able to order based on filename. The pattern I am regexping off of filenames looks something like `/\d{0,4}[-_]?/`

**Comment by slightlyoffbeat** [comment]
I am also used to the naming convention from Pattern Lab. Instead of buttons.html and type.html It could be 01-type.html and 02-buttons.html.  Also for materials: 01-atoms, 02-molecules, 03-organisms etc.

Just a suggestion. It was a pretty easy transition from pattern lab, but custom order is what I miss the most.

**Comment by lyzadanger** [comment]
One side effect to consider is the names that partials get registered as. Pattern Lab also applies the massaging to partial names (stripping off leading digits and dashes). Something to keep in mind!

**Comment by LukeAskew** [comment]
@lyzadanger @slightlyoffbeat  Just took a stab at this functionality. Check it out over at https://github.com/fbrctr/fabricator-assemble/pull/8

I'll probably just let this brew over the weekend and pull on Monday if all is well.
