### ISSUE TITLE
Some ideas and feedback

### ISSUE THREAD

**Issue by filtercake** [fbrctr/fabricator#128]
I played a bit with fabricator over the weekend (as I have with other styleguide/ui lib generators) and I like it a lot! Thx for making it!

I addded "contexts" like dark vs light backgrounds, or  point-and-click vs touch.

I changed the f-item partial to look like this:

```
// notes as usual
{{#if notes}}<div class="f-item-notes" data-f-toggle="notes">
	{{{notes}}}
</div>{{/if}}

/// item is kind of looping through all context variations, could be automated if you define the contexts centrally and how they express in code
// Context classes could on any parent element of the component. it is f-item here, in production probably the body for input and smaller containers for backgrounds.

<div class="f-item-preview context--light-background">
  {{{material @key @root}}}
</div>

<div class="f-item-preview context--light-background context--point-and-click">
  {{{material @key @root}}}
</div>


<div class="f-item-preview context--dark-background">
  {{{material @key @root}}}
</div>

<div class="f-item-preview jmd-context--dark-background jmd-context--point-and-click">
  {{{material @key @root}}}
</div>


<div class="f-item-code f-item-hidden" data-f-toggle="code">
	<pre><code class="language-markup">{{material @key @root}}</code></pre>
</div>
```

Some "mobile-first" CSS to that, meaning the touch (mobile) version is the default and the view adapts to "non-mobile":

```
// .f-item-preview gets some padding to show element with background around it
.f-item-preview {
  padding: 1em;
  margin-bottom: 1em;
}

// set background colors
.f-item-preview.context--light-background {
  background-color: rgb(203, 196, 188);
  color: black;
}

.f-item-preview.context--dark-background {
  background-color: rgb(37, 40, 42);
  color: white;
}

// .buttons size is decreased for in a point-and-click enviroment
.context--point-and-click .button {
  padding: 0.8em 2em;
}

```

looks like this:

![image](https://cloud.githubusercontent.com/assets/170145/7445858/d840b364-f1c4-11e4-9347-66239adc6fe9.png)

another thing: I would like to have front end matter for the docs, so I can specify a title within the doc, not just with the filename (saw that in another issue too). Might also just replace generated title with a top h1 if given in the doc.

To allow for ASCII doc, I changed line-height of `code` elements to 1.2

before:

![image](https://cloud.githubusercontent.com/assets/170145/7445882/b384de0a-f1c5-11e4-859a-ff85a0fe49b4.png)

after:

![image](https://cloud.githubusercontent.com/assets/170145/7445887/c0d243f4-f1c5-11e4-95ee-17bcabe7b740.png)

**Comment by LukeAskew** [comment]
Thanks for the feedback!

You light vs dark, click vs touch contexts are a good example of customizing the fabricator views to fit your needs. Thanks for sharing.

Good call on the docs title. I'll make sure to include that functionality when I work on the docs PR.

I saw your PR and will take a look.

:+1:
