### ISSUE TITLE
Using Fabricator in production

### ISSUE THREAD

**Issue by dennisimo** [fbrctr/fabricator#130]
What's the best way to serve Fabricator in non-dev environments, such as Heroku?

Is there a standardised way to get Fabricator to run on the default port for the environment, rather than :3000/:3001?

**Comment by LukeAskew** [comment]
Use the `build` script to generate an optimized build and deploy the artifacts in `dist`:

```
$ npm run build
``` 

Fabricator generates a static site in both dev and "build" modes; the latter performs additional optimizations to CSS and JavaScript for "production" consumption.

I typically deploy the entire build and use it both as a documentation site and CDN for my `toolkit.js`, `toolkit.css`, and image files. Other developers reference the deployed site when building their apps.

It's also a good idea to come up with some versioning strategy once you start deploying. I like using tags as deploy targets on my servers. e.g. `tags/v0.3.2` gets deployed to `http://website.com/toolkit/v0.3.2/` which allows devs to pull in specific versions of the toolkit code. `	<link rel="stylesheet" href="https://website.com/toolkit/v0.3.2/assets/toolkit/styles/toolkit.css">`
