### ISSUE TITLE
Changing default port number

### ISSUE THREAD

**Issue by emmareardon1** [fbrctr/fabricator#132]
Hi,

Please can you advise me:

You have a dependency for Fabricator to run on server 3000/3001. I have other dependencies which need to run on the same port. Is there a way to change / override the port that Fabricator runs on?

Thanks
E

**Comment by LukeAskew** [comment]
I believe BrowserSync will scan for the next available port automatically. If you have another app running on 3000/3001, the version of BrowserSync that Fabricator uses should use 3002/3003.

You can manually set the port by adding the config to the browsersync task:

https://github.com/fbrctr/fabricator/blob/198b788c6e1605de48109988fa7fe68b935fe887/gulpfile.js#L115
```
browserSync({
	server: {
		baseDir: config.dest
	},
        port: 9000,
	notify: false,
	logPrefix: 'FABRICATOR'
});
```

http://www.browsersync.io/docs/options/#option-port

**Comment by emmareardon1** [comment]
Thanks, i've added 9000 and Fabricator now loads up on 9000. 
However BrowserSync itself with its settings page is still running on 3001.

Fabricator loads first so takes the first available ports. Then I need to run another task afterwards which wants to run on 3001 and i'm unable to change this port without manually changing it inside a directory so would be easier for production to alter Browsersync.

Do you know what may be occurring to get it off 3001?

Thanks for your help.

**Comment by tonifisler** [comment]
Refer to BrowserSync documentation, I think you'll find your answer there: http://www.browsersync.io/docs/options/#option-ui

**Comment by emmareardon1** [comment]
Missed that! Thank you for all your help
