### ISSUE TITLE
ideas for distribution

### ISSUE THREAD

**Issue by VinSpee** [fbrctr/fabricator#133]
Anyone have a method for publishing the distributed toolkit? I'd love to be able to publish it as a node module and have `@import "toolkit"` reference my toolkit.

**Comment by jameswragg** [comment]
With [this advice](https://github.com/fbrctr/fabricator/issues/100#issuecomment-89004837) in mind, see [this](https://github.com/fbrctr/fabricator/issues/130#issuecomment-103523960) as one approach.

**Comment by LukeAskew** [comment]
@VinSpee I've not tried it, but I think you could publish your Fabricator instance to npm, then `@import 'node_modules/your-toolkit/src/assets/toolkit/styles/toolkit'`

@jameswragg :+1:

**Comment by VinSpee** [comment]
i ended up with this:

```js
{
  "name": "ui-kit",
  "version": "1.0.0-2",
  "description": "The LevelEleven UI Toolkit",
  "homepage": "http://ui-kit.leveleleven.com",
  "main": "dist/assets/toolkit/styles/toolkit.css",
  "files": [
    "dist/"
  ],
  "scripts": {
    "gulp": "gulp",
    "prestart": "npm install",
    "build": "npm install && gulp",
    "preversion": "npm run build",
    "postversion": "npm publish",
    "prepublish": "git push --tags && git push",
    "start": "gulp --dev",
    "test": "npm run build"
  }
}

```

I think it will work - I'm going to add another task for pushing to S3
