### ISSUE TITLE
Transfer *.JSON file from .src to .dist folder

### ISSUE THREAD

**Issue by Simeto** [fbrctr/fabricator#134]
Hello,

I,m working on a task with fabricator included.
I have one JavaScript module which uses .JSON file. This JSON is into .src/data/theJSONFile.json. But this folder doesn't compile into .dist folder. And my theJSONFile.json file doesn't read and render.

The Error which appesrs is : Failed to load resource: the server responded with a status of 404 (Not Found)                                                          http://localhost:3000/data/theJSONFile.json.

The JavaScript request is:  var theXMLHttpRequest = new XMLHttpRequest(); 
 theXMLHttpRequest.open('GET','/data/theJSONFile.json',true);

Is there a way when generated the styleguide this data folder to generate/compile too into .dist folder ?

Best Regards !

**Comment by LukeAskew** [comment]
Yup. I do this with a separate task using [gulp-yml](https://www.npmjs.com/package/gulp-yml)

```
var yml = require('gulp-yml');

gulp.task('data', function () {
	return gulp.src('src/data/**/*')
		.pipe(yml().on('error', gutil.log))
		.pipe(gulp.dest(config.dest + '/data'));
});
```

You'll also want to add `data` to the `assemble` watch task:

```
gulp.watch('src/**/*.{html,md,json,yml}', ['assemble', 'data']).on('change', reload);
```

And the `tasks` array in the `default` task:

```
// define build tasks
var tasks = [
	'styles',
	'scripts',
	'images',
	'data',
	'assemble'
];
```

**Comment by Simeto** [comment]
Thank you,

The approach works in my case.

Have a nice day !
