### ISSUE TITLE
run an existing fabricator instance (v 0.6.0) on another computer fails

### ISSUE THREAD

**Issue by TineBepunkt** [fbrctr/fabricator#138]
Hi there, 

I built my styleguide based on the verison 0.6.0. Everything works fine when I run it on my Computer. Now I wanted to run it on another computer, I installed node and tried to run my styleguide project by 'cd path/to/my/project and npm run dev'. It doesn't work, but the latest version of fabrictaor works...Is there a smart way to import my old fabricator src files to the latest version or any solution to run the old one?

**Comment by LukeAskew** [comment]
It'll probably be easier to get the older version working. What errors are you getting when you run on the new computer?

**Comment by TineBepunkt** [comment]
![errors](https://cloud.githubusercontent.com/assets/10288516/8210328/ce161a9e-1511-11e5-848b-acad31f66549.png)

**Comment by TineBepunkt** [comment]
I tried to download the blank version 0.6.0 and ran it the same way, this one worked but with errors as well...

**Comment by LukeAskew** [comment]
Looks an error with `gulp-sass`. Which version are you using?

You may need to delete the `node_modules` folder and `npm install` again with a different version.
