### ISSUE TITLE
Breaks in IE10/11: "Variable undefined in strict mode"

### ISSUE THREAD

**Issue by deepfriedmind** [fbrctr/fabricator#142]
![screenshot 2015-06-25 19 06 37](https://cloud.githubusercontent.com/assets/1065569/8360553/c4a1d7fc-1b6d-11e5-96bf-086ac3e28b20.png)

:point_up: This is the error received upon load in IE10/11 and causes all following scripts to break.

This is due to a combination of Prism not being fully compliant with ES5 strict mode (though I don't know why only IE complains) and Babel's automatic insertion of `'use strict';` statements.

I can currently think of 3 solutions:

**1:** Patch `src/assets/fabricator/scripts/prism.js` to instantiate `self` with `var`, i.e.:

```javascript
var self = (typeof window !== 'undefined')
	? window   // if in browser
	: (
		(typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope)
		? self // if in worker
		: {}   // if in node js
	);
```

(Prism already has at least 1 pull request for this but it has yet to be merged. PrismJS/prism#468)

**2:** Disable Babel's automatic insertion of `'use strict';` statements via `webpack.config.js` like so:

```javascript
module: {
    loaders: [
        {
            test: /\.js$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                blacklist: ['strict']
            }
        }
    ]
},
````

**3:** Exclude `prism.js` from babel-loader like so:

```javascript
module: {
    loaders: [
        {
            test: /\.js$/,
            exclude: /(node_modules|prism\.js)/,
            loaders: ['babel-loader']
        }
    ]
},
```

Personally, I went for number 3 seeing as Prism doesn't use any ES6 features anyways.

**Comment by rmpel** [comment]
i.m.h.o. solution 1 is the only valid; In javascript, you MUST use (ES5) var or (ES6) let/const to declare a variable. Thank you for pointing to where the error is, now I can fix my site :)
