### ISSUE TITLE
Sorting Materials

### ISSUE THREAD

**Issue by jonorherrington** [fbrctr/fabricator#143]
Hello -

I am trying to build an architecture inside the materials directory that would look like this

materials
|-- components
|-- structures
|-- formations

Is there any way to get the menu to sort this way with out too much messing around with the core of Fabricator? I know you can sort partials within those subdirectories by adding things like 01-filename.html, 02-filename.html. Just wondered if there was a way to do that with the side menu as well.

Thanks!

**Comment by LukeAskew** [comment]
The `materials` object doesn't have any sorting mechanism built in, but you can just construct the side menu manually. That's what I do in most cases.

https://github.com/fbrctr/fabricator/blob/fd68909092ca8fb85bdbd1928244a95295b6e425/src/views/layouts/includes/f-menu.html#L12

For instance, I have a toolkit that uses "typography", "elements", and "components", and I want them listed in that order. Here's a snippet of my `f-menu.html` file:

```html
<ul>
	...
	<li>
		<a href="typography.html" class="f-menu__heading">Typography</a>
		<ul>
			{{#each materials.typography.items}}
			<li>
				<a href="typography.html#{{@key}}">{{name}}</a>
			</li>
			{{/each}}
		</ul>
	</li>

	<li>
		<a href="elements.html" class="f-menu__heading">Elements</a>
		<ul>
			{{#each materials.elements.items}}
			<li>
				<a href="elements.html#{{@key}}">{{name}}</a>
			</li>
			{{/each}}
		</ul>
	</li>

	<li>
		<a href="components.html" class="f-menu__heading">Components</a>
		<ul>
			{{#each materials.components.items}}
			<li>
				<a href="components.html#{{@key}}">{{name}}</a>
			</li>
			{{/each}}
		</ul>
	</li>
	...
</ul>
```

**Comment by jonorherrington** [comment]
Awesome Luke! Thanks for the fast response. I figured you might have to hard code it. I just wanted to double check before I made any changes.

BTW Fabricator has been a huge asset to have. Thanks for all your hard work. You rock!

**Comment by LukeAskew** [comment]
Thanks for the props! Glad you're getting some use out of the tool.

**Comment by thetypebeast** [comment]
@LukeAskew Since this issue is similar to mine, I'll post here.

Since there's a way to specify ordering with materials, is it possible to add the feature to order views also? It would get around the issue of having to hard code the navigation, so that the menu can be constructed dynamically, just as it is with materials.

For example:
```
materials
|__ 01-components
|__ 02-structures
|__ 03-formations
views
|__ 01-design-standards
|__ 02-grid
|__ 03-pattern-library
```
