### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by ghost** [fbrctr/fabricator#145]
Hey @LukeAskew -

Have you considered including source maps as apart of one of the default gulp tasks? Every time we roll out fabricator we have to install this extra task as it is super helpful when dealing with Sass. I can create a pull request if you are down with this.

Thanks!

**Comment by LukeAskew** [comment]
Yeah absolutely, a PR is welcome. 

I don't use source maps, so I never incorporated that flow. I'm open to incorporated that feature as long as its not intrusive.

**Comment by jonorherrington** [comment]
@LukeAskew please feel free to close this. I originally opened this with an old account which I have since deleted. I don't have the ability to close it now :\. Sorry!
