### ISSUE TITLE
Passing YFM data/context to partials

### ISSUE THREAD

**Issue by asaeed** [fbrctr/fabricator#148]
Hi,

First, thank you ever so much for creating this most excellent project and sharing it with the world!
I have a question regarding passing data to handlebars partials.  I'm looking specifically at passing from material to material, in this case a simple form structure to a button component.

Here are my partials for form.html:

    <form action="">
      <div>
        {{> text-input}}
        {{> buttons.button text='Submit'}}
      </div>
    </form>

and buttons/button.html:

    <a href="#" class="btn btn-default">
      {{#if text}}
    	{{text}}
      {{else}}
    	Click
      {{/if}}
    </a>

Button correctly renders 'Click' if no data is passed in and renders 'Submit' if the form passes data using `{{> buttons.button text='Submit'}}`
Great!  but obviously passing parameters using this syntax is less than ideal when dealing with complex data objects.  Would be nice to be able to pass the already defined YFM at the top of a material/view.  Or better yet, the 'child' material could automatically inherit the 'parent' context.

Is this possible?  Have you ever considered this option instead of using json/yml files in the data folder?  Or am i just completely oblivious to something that should be obvious (very likely).

Here is what I'm hoping for and seems common in the Handlebars world:

    ---
    text: Submit
    ---
    <form action="">
      <div>
        {{> text-input}}
        {{> buttons.button this}}
      </div>
    </form>

or perhaps something like

    ---
    text: Submit
    ---
    <form action="">
      <div>
        {{> text-input}}
        {{#with this.context}}
          {{> buttons.button .}}
        {{/with}}
      </div>
    </form>

Thanks in advance!

**Comment by LukeAskew** [comment]
This is *somewhat* doable currently. You can pass YFM into a partial using explicit property names.

In your example: you should be able to do this:

```
---
text: Submit
---
<form action="">
  <div>
    {{> text-input}}
    {{> buttons.button text}}
  </div>
</form>
```

There is a little work that goes on behind the scenes to control scoping of YFM values during the templating cascade. You can't currently use the `this` keyword to refer to direct parent context, but you can use it within a block helper.

```
---
items:
  -
    text: Foo
  -
    text: Bar
---
<form action="">
  <div>
    {{> text-input}}
    {{#with items}}
      {{> buttons.button .}}
    {{/with}}
  </div>
</form>
```

```
<a href="#" class="btn btn-default">
  {{#if text}}
    {{text}}
  {{else}}
    Click
  {{/if}}
</a>
```

I think your request is valid; using a parent's context would be helpful. I can see what it would take to make that happen.

**Comment by asaeed** [comment]
Thanks for the response Luke.  Your first suggestion passing the variable directly in worked great.  The 2nd didn't work for me however.  The button doesn't render - as if "items" was an empty array.

I did find a workaround however which might suit me better than a YFM solution.  I'm going to use a simple handlebars helper as described here:
https://github.com/assemble/handlebars-helpers/blob/master/docs/helpers/data/helper-parseJSON.md
I like the idea of having the data defined inline as opposed to the top of the page.

gulpfile.js:

    gulp.task('assemble', function (done) {
        assemble({
            logErrors: config.dev,
            helpers: {
                parse: function(data, options) {
                  return options.fn(JSON.parse(data));
                }
            }
        });
        done();
    });

form.html:

    <form action="">
        <div>
            {{> text-input}}

            {{#parse '{ "text": "Submit" }'}}
                {{> buttons.button}}
            {{/parse}}
        </div>
    </form>

It's nice to have the option to define data 3 ways - in separate files, top of the file, or inline.  I will see how it plays out and what combination of these i end up using.
