### ISSUE TITLE
including other js

### ISSUE THREAD

**Issue by waltercruz** [fbrctr/fabricator#151]
Hi. Sorry if it's the wrong place to ask help. I want to include some js on my styleguide (bootstrap, jquery and other), but the scripts aren't being copied to the dist folder

I don't know that much about gulp either :(

My gulpfile:

https://gist.github.com/waltercruz/682ee79287dc071fa973

**Comment by jonorherrington** [comment]
@waltercruz on line 26 just have the object property "toolkit" have an array set as its value.

I.E.

    toolkit: [
        './src/assets/toolkit/scripts/toolkit.js',
	    './src/assets/toolkit/scripts/main.js'
    ]

You can do the same thing for the styles as well.

**Comment by jonorherrington** [comment]
Please note that by doing this when going to dist it will concat everything into toolkit.js so there won't be multiple files.

**Comment by waltercruz** [comment]
toolkit: [
				'./src/assets/toolkit/scripts/toolkit.js',
				'./src/assets/toolkit/scripts/jquery-1.11.3.js',
				'./src/assets/toolkit/scripts/bootstrap.js',
				'./src/assets/toolkit/scripts/bootstrap-maxlength.js',
				'./src/assets/toolkit/scripts/select2.js',
				'./src/assets/toolkit/scripts/select2_locale_pt_BR.js'
			]


error: Uncaught Error: Bootstrap's JavaScript requires jQuery

Any way to not compress things, or to require the scripts one by one, without concat/webpack?

**Comment by waltercruz** [comment]
(sorry if these questions are too basic)

**Comment by LukeAskew** [comment]
@waltercruz  This is a great question. 

There are some tips on the docs page referring to "Third Party Scripts". The best way to do this is probably will the scripts loader (built in). http://fbrctr.github.io/advanced/third-party.html#handling-modules-that-do-not-use-commonjs

Inside your `toolkit.js` should look something like this:

```javascript
require('script!./jquery-1.11.3');
require('script!./bootstrap');
require('script!./bootstrap-maxlength');
require('script!./select2');
require('script!./select2_locale_pt_BR');
```

**Comment by waltercruz** [comment]
err.. I solved! I thought that my scripts weren't working due to some compress, but it's ok, it's was a bug on my js itself :(

:)

Thank you for you code and patience!
