### ISSUE TITLE
hot wo reference images?

### ISSUE THREAD

**Issue by boehmatron** [fbrctr/fabricator#152]
I am trying to display images in my css using url('image.png') but no matter where I place the image, or which address I enter, the image seems not to be found and displayed.
I placed all my css in assets/toolkit/styles and my images are located in assets/toolkit/images

when I try to reference the image in my css with the path '../images/image.png' it does not work. Any ideas?

**Comment by LukeAskew** [comment]
`background-image: url('../images/pattern.jpg');` should work.

The compiled asset directory places the `images` directory as a sibling of `styles` under `dist/assets/toolkit`

Does the `dist/assets/toolkit` directory contain all the expected files?

**Comment by chrisk2020** [comment]
If you've been running `gulp serve` you may need to run the default `gulp` task to give the images task a hand creating the correct directories in `dist`

**Comment by bitlinguist** [comment]
Wow! Thanks. Why does fabricator create a dist file? Does anyone know something I can read on this?

**Comment by LukeAskew** [comment]
@bitlinguist the `dist` folder is the static output of Fabricator. It is like a web root - it is where the dev live reloading (BrowserSync) server serves from, and is the artifacts you can deploy to any hosting environment.

**Comment by LukeAskew** [comment]
@chrisk2020 is also right. I've had issues with Gulp watch not working when the folder is empty on startup. You may need to restart the dev environment `$ npm start` after adding your first images.

**Comment by nickmjones** [comment]
This still isn't working for me. I have an image at `dist/assets/toolkit/images/avatar.jpg` that I'm trying to render with `<img src="../images/avatar.jpg" class="avatar">` to no avail. I've run the default gulp task and restarted the server with `npm start`. Any thoughts? How am I screwing this up?

**Comment by Webtransformer** [comment]
I change a few things in my setup but I am using following code:
`<img class="img-responsive" src="./{{baseurl}}/static/images/xxx.jpg" alt="">`
