### ISSUE TITLE
Prism.js breaks menu toggle on IE9-11.

### ISSUE THREAD

**Issue by mandalatv** [fbrctr/fabricator#153]
When viewing my Fabricator instance in IE the menu is suppressed and won't toggle. I wasn't seeing any JS console errors. 

I've found that downloading the default development version here: [http://prismjs.com/download.html] (http://prismjs.com/download.html) and replacing src/assets/fabricator/scripts/prism.js restores functionality.

**Comment by LukeAskew** [comment]
I believe this is a duplicate of #142 and is fixed by #149.

New release coming soon.

**Comment by ericwisehammer** [comment]
Hey there,

I don't mean to gravedig on this but I can confirm the newest version of Fabricator has this issue in IE11 and the same resolution proposed by @mandalatv still successfully resolves it.
