### ISSUE TITLE
Possible to use one fabricator project to create multiple toolkits?

### ISSUE THREAD

**Issue by dietergeerts** [fbrctr/fabricator#154]
I was wondering if it is possible now to do this? Like I have one fabricator instance/project and then different folders for each of my toolkits. I could then just build the toolkit by giving the folder path from where to take the sources.

If not, then could this be made possible? I see benefits in this like updating the version of your fabricator instance, adapting the fabricator project for our needs for use with multiple toolkits, etc...

**Comment by LukeAskew** [comment]
I don't see why you couldn't do this.

The `gulpfile.js` and `assemble()` task are designed to be configurable. You should be able to organize your fabricator folders however you want to achieve this organization, then configure the tasks to point at the correct files.

It will get a little tricky with gulp builds, especially with the live-reload dev environment. You'd want a setup that avoids re-compiling styles/scripts/templates across every toolkit. You'd also need separate `assemble()` tasks per toolkit if you want them to have unique data contexts.

**Comment by dietergeerts** [comment]
Hi, I was thinking more in a way where this fabricator would be a node module that will be used to build the actual toolkit. This way, we can benefit from using newer versions in already existing toolkits. Don't know if you like this idea, but if you do, I would gladly help you.

**Comment by tonifisler** [comment]
Yeoman is the way to go just for that.

We actually already built a Yeoman generator on top of Fabricator to help us with the setup of new projects. Fabricator is a standard node dependency and everything is running really smoothly. Go have a look at our "Toolbox" for inspiration maybe: http://frontend.github.io/toolbox/

**Comment by dietergeerts** [comment]
@tonifisler, but what when for example the ability to use multiple config files is added to fabricator? You can't update your toolkit after it has been generated. You'll have to edit it manually.

The config files I speak of is what I need to have now. We have multiple clients and all want to use different colors etc..., so we need to build the toolkit with different configurations.

What I am thinking to do is have fabricator as a node dependency, and only have the actual files/components/etc... in our toolkit, ow, and a file that will hold the configuration. This way we can benefit from extra features/bugfixes etc.. in the future.

Yeoman could then be used to startup the project, that Í am aware of, and will be the next step to fasten our toolkit development.

**Comment by dietergeerts** [comment]
Hi, I forked and created something what I had in mind. Not finished, but good for what I need right now.  Maybe you can look at it? https://github.com/dietergeerts/fabricator. This way I can have another project use this to build the toolkit and only having the files specific to the toolkit and not the whole build process. Please let me know what you think of it.
