### ISSUE TITLE
Error when using array of data sources

### ISSUE THREAD

**Issue by dietergeerts** [fbrctr/fabricator#155]
Hi, when setting the data option as this:

```
// assemble
gulp.task('assemble', function (done) {
	assemble({
		logErrors: config.dev,
		data: ['package.json', 'src/data/**/*.{json,yml}']
	});
	done();
});
```

I got following error:
```
Error (fabricator-assemble): JS-YAML: end of the stream or a document separator is expected at line 1, column 13:
    'use strict';
```

When using them seperate, I got no issues.

**Comment by dietergeerts** [comment]
While figuring this one out, I see that when setting the default in assemble to an array, all works. It seems that the following line is messing things up when one is an array and the other a string:

```
// merge user options with defaults
options = _.merge({}, defaults, userOptions);
```

I'll see to fix it and do a pull request on the fabricator-assemble repo is this ok?

**Comment by dietergeerts** [comment]
I actually don't know if it must be solved in fabricator-assemble, as it's actually the lodash merge method that doesn't do what it's supposed to do, no? Any thoughts?

**Comment by LukeAskew** [comment]
Thanks for tracking this down. 

I think you're correct that the `_.merge` doesn't handled a string vs array.

I made the default option an array, and that seems to work in every case. Check it out. https://github.com/fbrctr/fabricator-assemble/pull/17/files

**Comment by dietergeerts** [comment]
Hi, I filed that bug in the lodash project and they already fixed it: https://github.com/lodash/lodash/issues/1375
Now just waiting to have it released with a new version on npm.
