### ISSUE TITLE
Having two files with the same name breaks the menu highlighting

### ISSUE THREAD

**Issue by LeBenLeBen** [fbrctr/fabricator#156]
I have two `forms.html` files in my materials, one in a "components" folder, the other in "structures". When I’m on the second one, its the menu item corresponding to the first one that is highlighted.

As far as I can see the code doesn’t pay attention to the current group or category. Do you have any recommendation on how you’d fix this? I could try patching it and do a PR then.

**Comment by LukeAskew** [comment]
Hmm this is a tricky one. You're correct in that the `setActiveItem()` function in `fabricator.js` doesn't account for anything other than the hash. It assumes a 1:1 between hash:id.

A solution might be to modify the `parsedItems` and `setActive` functions to include the `location.pathname`.
