### ISSUE TITLE
Unable to order Folders 

### ISSUE THREAD

**Issue by rafal-leap** [fbrctr/fabricator#159]
Is the a way to oder folders? At the moment my structure is like bootstrap eg:

*- materials
*|---components
*|-------dropdowns
*|-------labels
*|-------navs
*|---css
*|-------buttons
*|----------01-basic.html
*|----------02-disabled.html
*|-------checkboxes
*|-------grid

so I'm able to order any file within the folder but if I rename the folder to eg: 01-buttons, 02-components gulp crashes...

Thanks

**Comment by jonorherrington** [comment]
Hey @rafal-leap this was answered in #143

**Comment by rafal-leap** [comment]
Hi Mate
Thanks for that...this helps for the very top level sorting but if I have the second level like here:

*- materials
*|---components
*|-------dropdowns
*|-------labels
*|-------navs
*|-------badges.html

I will have to do every folder manually...a bit of pain.

**Comment by LukeAskew** [comment]
@rafal-leap just opened a PR that adds this functionality. Mind checking it out and testing it? https://github.com/fbrctr/fabricator-assemble/pull/20
