### ISSUE TITLE
Latest Release

### ISSUE THREAD

**Issue by jonorherrington** [fbrctr/fabricator#163]
Hey @LukeAskew,

Is there a reason v1.1.1 is still marked as the latest release? Just want to make sure there are no bugs in the v.1.1.1+ versions.

Thanks!

**Comment by LukeAskew** [comment]
Nah, just me being lazy and not creating releases for each tag. 

Created a release for the latest tag https://github.com/fbrctr/fabricator/releases/tag/v1.2.2
