### ISSUE TITLE
Require jquery for bootstrap (both via bower_components)

### ISSUE THREAD

**Issue by saulide** [fbrctr/fabricator#167]
Hello, im getting problems requiring jQuery for bootstrap. I followed the wiki and i have in toolkit.js following lines

var $ = require('jquery'); // Exists also in npm
require('imports?$=jquery!bootstrap/dist/js/bootstrap.js');

As an error i get:
Uncaught Error: Bootstrap's JavaScript requires jQuery

How should i add the bootstrap javascript files and expand those with my own javascript?

**Comment by LukeAskew** [comment]
Bootstrap expects the longform `jQuery` and not `$`, so your require statement should look like:

```
require('imports?jQuery=jquery!bootstrap/dist/js/bootstrap');
```
