### ISSUE TITLE
Class consistency

### ISSUE THREAD

**Issue by willium** [fbrctr/fabricator#168]
The pattern for all classes dictated by fabricator should have a `-f-` prefix but do not. While not strictly necessary, I am attempting to style all elements that are not dictated by fabricator. This breaks several cases -- most notable along the menu within the list items. They do not have a class at all (let alone a -f- prefix), and therefore cannot be selected against by my toolkit's CSS. Same goes for the h1 atop each container, the code, and the notes.

**Comment by LukeAskew** [comment]
I'm not I understand the issue.

The menu is wrapped with a parent `.f-menu` div. Items are wrapped with `.f-item-group`. You should be able to leverage those classes in you stylesheet as needed.

You can also add or remove classes from the fabricator layouts as needed. It's totally meant to be modified.
