### ISSUE TITLE
data not working within {{#iterate}}

### ISSUE THREAD

**Issue by deepfriedmind** [fbrctr/fabricator#169]
The following example doesn't produce any output:

```handlebars
{{#iterate 2}}
    {{some.data.here}}
{{/iterate}}
```

[This helper](https://github.com/diy/handlebars-helpers/blob/master/lib/repeat.js), for example, serves the same purpose and works fine.

**Comment by LukeAskew** [comment]
I'd just use that repeat helper for now.

The plan is to create a helpers repo to store/facade useful helpers like this. I'll probably just ditch `iterate` in favor of the one that linked to since it appears to work better.

see https://github.com/fbrctr/fabricator-assemble/issues/22
