### ISSUE TITLE
Issue with Materials

### ISSUE THREAD

**Issue by jonorherrington** [fbrctr/fabricator#170]
I found an issue inside the materials section (i.e. components and structures). The problem is this. If say inside components you have a directory architecture that looks like this:

components/
|--directoryname/
|----filename.html
|----filename.html
|--directoryname/
|---filename.html

When you run fabricator, the left hand menu does not show any menu items under the components section. It is not until you change that architecture to this:

components/
|--filename.html
|--directoryname/
|----filename.html
|----filename.html
|--directoryname/
|---filename.html

That menu items begin to get built out when running fabricator. Any suggestions on how to fix this bug?

**Comment by LukeAskew** [comment]
This might be related to https://github.com/fbrctr/fabricator-assemble/issues/21

Try updating `fabricator-assemble` and see if that works.

**Comment by jonorherrington** [comment]
Ahh sorry @LukeAskew. I thought I saw that issue reported before but when I was looking for it, I couldn't find it. 

Yep that did it. Thanks for the help!
