### ISSUE TITLE
Any reason for using gulp-imagemin?

### ISSUE THREAD

**Issue by mik01aj** [fbrctr/fabricator#182]
`gulp-imagemin`, when installed, takes around 100MB of space (with `npm@2`). It requires compiling binary packages, that have `postinstall` tasks, thus slowing down `npm install`. On the other hand, I don't see a reason to optimize all the images just for the style guide. Maybe it could be removed? Or am I missing something?

**Comment by LukeAskew** [comment]
Great question. In my experience, toolkits often have some level of imagery (icons, placeholders, etc). Imagemin is in place to ensure whatever assets you include get optimized. I've also found it helpful in providing a benchmark for page weight. When my toolkits get integrated, I can point back to the Fabricator pages and compare page weight pretty easily.

Gulp is pretty modular, so you can remove the dependency in your fabricator instance without affecting too much.
