### ISSUE TITLE
Using different data for a material and its parent

### ISSUE THREAD

**Issue by nategreen** [fbrctr/fabricator#189]
I'm guessing this is a bug with my code, not yours. I can't think of a reason why this shouldn't work, but maybe I don't quite understand how Fabricator is supposed to be used.

Basically, I've got two files:

## button.html:

```html
---
notes: |
  For some reason, I can't get this button to render properly while also rendering the button group properly.
label: "Button"
primary: false
disabled: false
---
{{#if href }}
    <a href="{{ href }}" alt="{{ alt-text }}" class="button{{#if primary}} primary{{/if}}">{{ label }}</a>
{{ else }}
    <button class="{{#if primary}}primary{{/if}}"{{#if disabled}} disabled{{/if}}>{{ label }}</button>
{{/if}}
```
and

## button-group.html:

```html
---
buttons:
  button:
    label: "Button"
  primary-button:
    label: "Primary button"
    primary: true
  disabled-button:
    label: "Disabled button"
    disabled: true
  link-button:
    label: "Link button"
    href: "#"
    alt-text: "A link that looks like a button"
  primary-link-button:
    label: "Primary link button"
    primary: true
    href: "#"
    alt-text: "A link that looks like a primary button"
---

<div class="button-group">
  {{#each buttons}}
    {{> button }}
  {{/each }}
</div>
```
For some reason, when I include the label in the front matter of `button.html`, all the buttons in `button-group.html` are shown with no labels. If I remove the label from `button.html`, the labels are all fine in the button group, but obviously there is no label on the single button.

I feel like maybe I'm missing something obvious. Any ideas?

**Comment by LukeAskew** [comment]
It's maybe not so obvious :) . I think could be a bug.

Are these files in a subdirectory?

**Comment by nategreen** [comment]
At the moment, they're all in `src/materials/components` but I've also tried putting `button-group.html` in `src/materials/structures` and it didn't seem to make a difference (except that it was in a different place in the navigation, and all that).

**Comment by nategreen** [comment]
Trying to use Fabricator for something again this week, but having the same problem. Using `{{material "button" this}}` in the button group material renders properly...except that the angle brackets and such get encoded before it gets put out to the Fabricator site. :disappointed: 

![image](https://cloud.githubusercontent.com/assets/6674698/13890270/f2d5bfb4-ed20-11e5-805f-64a3db247237.png)

Seems like the issue is probably related to #238, #208 and/or #195.

**Comment by iamkeir** [comment]
@nategreen I found that using three curly braces prevents encoding, e.g. `{{{ variable }}}` - not sure if that works in this context though.

**Comment by nategreen** [comment]
Thanks @iamkeir. I feel like maybe I tried that, but I'll have to try it again next time I get Fabricator out.
