### ISSUE TITLE
WebComponents Implementation/Fork

### ISSUE THREAD

**Issue by csengineer13** [fbrctr/fabricator#205]
Just a thought/discussion item.

Now that the Microsoft Edge team has declared the development of the WebComponent's spec a priority, it would be cool to see an implementation/fork of Fabricator where the "Components" are either:

- [Vanilla WebComponents](http://webcomponents.org/)
- [Polymer WebComponents](https://www.polymer-project.org/1.0/)

Also, now that the template element is finalized in the newest versions of all browsers, it might be interesting to consider using vanilla templates in Fabricator's implementation as well (eventually).

For the curious, still waiting on two major pieces of WebComponents to finish implementation in IE:

- [ShadowDOM](https://dev.windows.com/en-us/microsoft-edge/platform/status/shadowdom)
- [CustomElements](https://dev.windows.com/en-us/microsoft-edge/platform/status/customelements)

The HTML Import portion of the spec will likely be abandoned in favor of ES6 Module Loading.

--
Again, just thinking out loud. This area isn't me forte, but I do enjoy watching this project progress.

**Comment by LukeAskew** [comment]
This is an interesting idea. I don't know much about web components, but I'll keep it in mind as I work on improving the project.

I've tried to keep Fabricator as flexible as possible, so I imagine it'll just be a matter of staying out of the way and making use of web components a seamless experience.
