### ISSUE TITLE
Nested partials

### ISSUE THREAD

**Issue by roundrobin** [fbrctr/fabricator#208]
Is it possible to use a partial within a partial?

I tried doing it, but I get a parsing error:
```
Error: Parse error on line 5:
...                {{&gt; app.chat-header}
----------------------^
Expecting 'ID', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
```

**Comment by LukeAskew** [comment]
Should be possible. Looks like the `>` is getting encoded. Is that something you have in your template or is Fabricator encoding it?

The syntax for partials is `{{> partialName}}`

**Comment by roundrobin** [comment]
Hm, maybe my structure is incorrect:

I am usually calling the partial in a template in `views/pages` like this `{{> app.chat-header}}` but in case of the nested partial call I am doing it in the `materials/structures/app` folder with `{{> partialName}}` by referencing a partial in the same folder....
