### ISSUE TITLE
Building for a sub-directory deploy

### ISSUE THREAD

**Issue by danrichman** [fbrctr/fabricator#211]
Was wondering if you could give some guidance on how to get the default instance to work in a sub-directory instead of the root. This built style guide will have to reside on a server at: *domain.com/styleguide*

But the static files all seem to be expecting absolute URLs as a root-directory install. Is there an easy way to reconfigure the default install? If there is, I missed it (sorry). Thanks so much.

**Comment by LukeAskew** [comment]
This is something I have marked as a priority improvement when I have more time to work on the project. Currently, the easiest way would be to define your own version of the `{{baseurl}}` property in a global data file (`src/data/config.json`) and give it a value like `/styleguide`.

You could then use it like: `src="{{config.baseurl}}/assets/toolkit/styles/toolkit.css"`.

**Comment by maljones** [comment]
I'm suddenly needing this as well so I can have multiple toolkits under one URL. I tried the baseurl redefinition and it borked out:
`Error (fabricator-assemble): missed comma between flow collection entries at line 3, column 14:
        "baseurl": "learner"`

This is all I have in my new config.json file:

`{
    // built-in props
    "baseurl": "/learner"
}`

I'm guessing I'm missing something really obvious.

**Comment by LukeAskew** [comment]
Hmm. Not sure. I just tried using that same bit of JSON and it worked. Let me know if you figure it out.

**Comment by maljones** [comment]
It's the best kind of bug then... I'll let you know if I figure something else out. Was there any other declaration or wrapper in your config.json?

**Comment by LukeAskew** [comment]
Nope. You can try writing in yml to see if that helps.

**Comment by createlogic** [comment]
Hi,

For multiple languages I want to use "en" and "ar" directories within data and then depending on "lang:en" or "lang:ar" gray matter variable.

Regards,
Bilal
