### ISSUE TITLE
Scss partials aren't compiling correctly

### ISSUE THREAD

**Issue by joeyfigaro** [fbrctr/fabricator#227]
Attempting to set up subdirectories for my styles and the resulting ```toolkit.css``` doesn't seem to be picking up any changes. Any ideas? 

### directory setup
![](https://s3.amazonaws.com/f.cl.ly/items/1p2X1T3P2h1z0G012a0l/Image%202016-01-17%20at%2010.07.32%20AM.png?v=a7019573)

### contents of toolkit.scss
```scss
/**
 * Toolkit styles
 */

@import 'utilities/colors';

@import 'global/typography';

@import 'elements/buttons';
```

### contents of toolkit.css
```css
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJ0b29sa2l0LmNzcyIsInNvdXJjZVJvb3QiOiIvc291cmNlLyIsInNvdXJjZXNDb250ZW50IjpbXX0= */
```

**Comment by jonorherrington** [comment]
I know this might sound like a silly question but do you have anything inside of those three partials?

**Comment by joeyfigaro** [comment]
@jonorherrington Not silly at all -- they've all got content, yes.

**Comment by LukeAskew** [comment]
Hmmm everything looks right. Any console errors? Tried restarting the `npm start` task?

**Comment by vjandrei** [comment]
I have the same problem here. I am trying to import .scss file from the same folder ad the toolkit.scss but getting this error `Error in plugin "sass"
Message:
    src/assets/toolkit/styles/toolkit.scss
Error: File to import not found or unreadable: ./ds-style.scss.
        on line 5 of src/assets/toolkit/styles/toolkit.scss
>>  @import "./ds-style.scss";

   -^`
