### ISSUE TITLE
Should use normalize as default

### ISSUE THREAD

**Issue by Sensiblemnd** [fbrctr/fabricator#234]

**Comment by jonorherrington** [comment]
Again people like to use different css resets. Not everyone uses normalize. I don't think this should be baked into vanilla Fabricator.

-1

**Comment by larrybotha** [comment]
agreed, fabricator's styles should all be namespaced so as to reduce any conflicts with whichever css anyone imports. A reset affects styles globally, yielding different styles from what someone may expect in production.
