### ISSUE TITLE
Bootstrap 4 implementation

### ISSUE THREAD

**Issue by achtan** [fbrctr/fabricator#237]
Hi, (I am new in here)
how can I add bootstrap 4 to my fabricator project?

i installed BS like this: `$ npm install --save bootstrap@4.0.0-alpha.2`, but what now? How do I init BS code, and how do I 'export it' to `/dist/asset/...` ?

**Comment by LukeAskew** [comment]
For the css, you'd import the sass into `toolkit.scss`:

```
@import '../../../../node_modules/bootstrap/scss/bootstrap';
```

And import the js in your `toolkit.js`, probably something like:

```
require('bootstrap');
```

Not 100% sure - I haven't tried this before. You may need to leverage the scripts or imports loaders. More info here: https://fbrctr.github.io/advanced/third-party.html

**Comment by achtan** [comment]
scss is working fine, but in js i got this error `Uncaught ReferenceError: jQuery is not defined`
so I installed jQuery with `npm install --save-dev jquery` but still the same error

my toolkit.js
```
var $ = require('jquery');
var jQuery = $;
var bootstrap = require('bootstrap');
```

**Comment by LukeAskew** [comment]
Use the imports loader
```
require('imports?jQuery=jquery!bootstrap');
```

**Comment by achtan** [comment]
not working, still the same error

**Comment by achtan** [comment]
can u please reopen this issue?

**Comment by DJTB** [comment]
This isn't specific to fabricator at all, so you're unlikely to see further discussion.

Try giving this a go.
In your webpack.config.js you can expose any libraries from node_modules ('npm install'ed locally) to your all your toolkit JS files as global variables
```
var config = {
   /*  
   * entry, output, module etc 
   */
    plugins: [
      new webpack.ProvidePlugin({
        "$": "jquery",
        "bootstrap": "bootstrap"
      })
    ],
    cache: {}
  };
```

the ProvidePlugin format to expose global variables is
`"variableName": "npm/node_modules package name"`

Good luck.

**Comment by niho28** [comment]
@achtan did you ever get this working correctly?. I have tried pretty much everything including suggestions here. Only using cdns has worked!

**Comment by achtan** [comment]
try this:
````
'use strict';
require('imports?jQuery=jquery!bootstrap-sass/assets/javascripts/bootstrap');
var $ = require('jquery');
$('.dropdown-toggle').dropdown();
`````

and add to your `webpack.config.js` bootstrap loader
``````
var path = require('path');
var webpack = require('webpack');

module.exports = function(fabricatorConfig) {

	"use strict";

	var config = {
		entry: {
			'fabricator/scripts/f': fabricatorConfig.src.scripts.fabricator,
			'toolkit/scripts/toolkit': fabricatorConfig.src.scripts.toolkit
		},
		output: {
			path: path.resolve(__dirname, fabricatorConfig.dest, 'assets'),
			filename: '[name].js'
		},
		module: {
			loaders: [
				{
					test: /\.js$/,
					exclude: /(node_modules|prism\.js)/,
					loaders: ['babel-loader']
				},

				{
					test: /\.less$/,
					loader: "style!css!less"
				},

				// **IMPORTANT** This is needed so that each bootstrap js file required by
				// bootstrap-webpack has access to the jQuery object
				{ test: /bootstrap\/js\//, loader: 'imports?jQuery=jquery' },

				// Needed for the css-loader when [bootstrap-webpack](https://github.com/bline/bootstrap-webpack)
				// loads bootstrap's css.
				{ test: /\.woff(\?v=\d+\.\d+\.\d+)?$/,   loader: "url?limit=10000&minetype=application/font-woff" },
				{ test: /.woff2?(\?v=\d+.\d+.\d+)?$/,    loader: "url?limit=10000&minetype=application/font-woff" },
				{ test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,    loader: "url?limit=10000&minetype=application/octet-stream" },
				{ test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,    loader: "file" },
				{ test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,    loader: "url?limit=10000&minetype=image/svg+xml" }
			]
		},
		plugins: [],
		cache: {}
	};

	if (!fabricatorConfig.dev) {
		config.plugins.push(
			new webpack.optimize.UglifyJsPlugin()
		);
	}

	return config;

};
`````

**Comment by niho28** [comment]
ok thanks I will try it.

Do you have to run any command after in gulp for it to pick it up?

**Comment by schmalaa** [comment]
If you are here via google, I had to add jquery to window. Hope this helps others in the same boat as I.

`window.jQuery = window.$ = require('jquery');`

**Comment by Sensiblemnd** [comment]
I incorporated bootstrap sass in the link below. It has been a while but this might give you an example on how to do  it

https://github.com/Sensiblemnd/fabricator-bootraps-es6
