### ISSUE TITLE
Generating a new toolkit folder into dist/assets/toolkit

### ISSUE THREAD

**Issue by jraeruhl** [fbrctr/fabricator#239]
I have added a "fonts" folder to house our icon font files within src/assets/toolkit/. I can not get the folder to generate within dist/assets/toolkit to be visible by the browser. I have added the following chunks of code to gulpfile.js, (but they are just guesses). They are not throwing any errors, but they are not generating the results I am looking for either. 

```
var config = {
	dev: gutil.env.dev,
	src: {

        // added code

        fonts: {
			toolkit: 'src/assets/toolkit/fonts/*'
		},

        // end of added code

        // ...

	},
	dest: 'dist'
};

```

```
gulp.task('fonts', function () {
	return gulp.src(config.src.fonts)
		.pipe(gulp.dest(config.dest + '/assets/toolkit/fonts'));
});

```

```
gulp.task('serve', function () {

       // ...

       // added code

       gulp.task('fonts:watch', ['fonts'], reload);
       gulp.watch(config.src.fonts, ['fonts:watch']);

       // end of added code
});

```

``` 
// default build task
gulp.task('default', ['clean'], function () {

	// define build tasks
	var tasks = [
		'styles',
		'scripts',
		'images',
        'fonts',     // added line
		'assemble'
	];

	// ...

});

```

**Comment by LukeAskew** [comment]
Did you restart gulp?

**Comment by jraeruhl** [comment]
Hmm. Just added the following code to watch and restart gulp as needed:

```
gulp.slurped = false; // step 1

gulp.task("watch", function(){

    if(!gulp.slurped){ // step 2
        gulp.watch("gulpfile.js", ["default"]);
        gulp.watch("etc...");
        gulp.slurped = true; // step 3
    }

});

```
That doesn't seem to be doing the trick. So, I did another `npm start` to find the project wouldn't load. Backtracked my code additions. All works fine until I add the line indicated below.

``` 
gulp.task('default', ['clean'], function () {

	// define build tasks
	var tasks = [
		'styles',
		'scripts',
		'images',
         'fonts',     // adding this line throws an error
		'assemble'
	];

	// run build
	runSequence(tasks, function () {
		if (config.dev) {
			gulp.start('serve');
		}
	});

});

```
My error is: 

[11:33:18] Starting 'fonts'...
[11:33:18] 'fonts' errored after 122 μs
[11:33:18] Error: Invalid glob argument: [object Object]

Any idea what I might be missing in the previous chunks of code added?

TIA

**Comment by citation-nm** [comment]
Here's how I achieved working with web fonts:

After the 'favicon' gulp task I added

```
// fonts
gulp.task('fonts', function () {
  return gulp.src(config.src.fonts)
    .pipe(gulp.dest(config.dest + '/assets/toolkit/fonts'));
});
```

Then in the collection of gulp server tasks I added

```
  gulp.task('fonts:watch', ['fonts'], reload);
  gulp.watch(config.src.fonts, ['fonts:watch']);
```

Finally in the list of build tasks I added

```
  // define build tasks
  var tasks = [
    'styles',
    'scripts',
    'images',
    'fonts',
    'assemble'
  ];
```

Hope this helps.

**Comment by jraeruhl** [comment]
Yes @citation-nm! This worked with the addition of the following to the config variable.

```
fonts: 'src/assets/toolkit/fonts/*'
```

Thank you!!

**Comment by citation-nm** [comment]
Good stuff

**Comment by LukeAskew** [comment]
:clap:

**Comment by Wyzerus** [comment]
Ching Ching! Thanks
