### ISSUE TITLE
Change {{baseurl}} on build?

### ISSUE THREAD

**Issue by Sensiblemnd** [fbrctr/fabricator#244]
I noticed that when you run the build the base URL will go to / 
I need it to not have that

**Comment by Sensiblemnd** [comment]
More details when I do a build the html is deployed to a subfolder in a domain foo.com/build.
Now since the URL of all scripts in the html start with /asset/ all css and js are trying to load from the root which breaks the site.

**Comment by halovanic** [comment]
Adding this else block to the fabricator-assemble script resolved the issue for me:

```javascript
if (collection) {
	pageMatter.data.baseurl = '..';
} else {
	pageMatter.data.baseurl = '.';
}
```
 It should make all paths using baseurl relative.
