### ISSUE TITLE
how to add layout to the /views/pages/*.html

### ISSUE THREAD

**Issue by achtan** [fbrctr/fabricator#245]
in my `/views/pages/foo.html` i have:
````
---
title: Foo | Fabricator
layout: default
---

<h1>Hello, World!</h1>
````

but page is rendered without any layout

**Comment by achtan** [comment]
sry my bad, ist working fine!

**Comment by LukeAskew** [comment]
For the curious:

`layout` is a reserved front-matter keyword that refers to layout files in the `src/views/layouts` directory. The default layout is `default.html`, but you can add different layout templates, then tell a page template to use it by defining the `layout` property in the template's front-matter. The value is the name of the file, without the extension.
