### ISSUE TITLE
f-item-preview vs. rendered f-item-code

### ISSUE THREAD

**Issue by ngov** [fbrctr/fabricator#251]
I saw what @filtercake had done in his custom f-item-context.html layout so that the f-item-code generates a more dynamic preview while still rendering exactly what is in the material/*.html, but is there any other way around this? 

My use case is the following:
```

<a type="button" class="btn btn-default">Default</a>
<button type="button" class="btn btn-default">Default</button>
<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-info">Info</button>
<button type="button" class="btn btn-warning">Warning</button>
<button type="button" class="btn btn-danger">Danger</button>
<button type="button" class="btn btn-link">Link</button>
<div class="btn-ex-wrapper">
	<button class="btn btn-tertiary">Tertiary</button>
</div>
```

I don't want the `<div class="btn-ex-wrapper">` to render in the preview.

**Comment by LukeAskew** [comment]
I'm not sure there is a way around this. 

On a side note, I suggest breaking each one of those buttons out into a separate file and grouping them in a `buttons/` folder so you can access them in other components and templates as `{{> buttons.default}}` `{{> buttons.success}}` etc.
