### ISSUE TITLE
userhelper referencing Handlebars.helpers.material

### ISSUE THREAD

**Issue by genmacg** [fbrctr/fabricator#253]
I created a user helper in gulpfile.js where I reference the materials helper you use for assembling the views. The helper looks something like this (what it does is not really relevant):

```
userHelper: function (name, context, list, item) {
    console.log(Handlebars.helpers);
    return Handlebars.helpers.material(name, context[list][context.config.case][item], {hash:null});
}
```

on my machine, assembling works fine. Logging the helpers shows my user helpers as well as the material helper being available. When running on a colleagues machine, we get an error, stating that the material helper is not defined. We are both running the same version of node, npm, etc. Does anybody have an idea, why this difference occurs where I can access the material helper in the gulpfile, and he can't?

**Comment by LukeAskew** [comment]
Hope you figured this out!
