### ISSUE TITLE
Remove soucemap from js and css on build

### ISSUE THREAD

**Issue by Sensiblemnd** [fbrctr/fabricator#254]
How do I automatically remove the sourcemap from the js and css files on build?

**Comment by qaid** [comment]
I see the command to write sourcemaps in two places in `gulpfile.js`:

- Around line 59, in the context of fabricator styles: `.pipe(sourcemaps.write())`
- Around line 70, in the context of toolkit styles: `.pipe(gulpif(config.dev, sourcemaps.write()))`

Perhaps removing or commenting out one or both of those lines would do the trick?

**Comment by berkandirim** [comment]
@Sensiblemnd if you pass an empty string `sourcemaps.write('')`, then you have a separate map file. You could than add it to .gitignore if you don't want to deploy those files.
