### ISSUE TITLE
Partial block

### ISSUE THREAD

**Issue by EmilTemirov** [fbrctr/fabricator#256]
Is it possible to use the partial blocks? http://handlebarsjs.com/partials.html#partial-block
I'd like to be able to use the following:
`{{#> raised-button}}Save{{/raised-button}}`

**Comment by LukeAskew** [comment]
No but I want to look into this.

**Comment by orangehaze** [comment]
This would be incredibly useful as it would allow partials to get passed up to their parents and reduce copy/pasting markup.

**Comment by orangehaze** [comment]
@EmilTemirov, it looks like it is working in 1.2 as it has a later version of Handlebars.
