### ISSUE TITLE
Settings in gitattributes can damage images

### ISSUE THREAD

**Issue by derheap** [fbrctr/fabricator#258]
We use Fabricator to build a styleguid and included images as placeholders.
When we cloned the repo on a different machine the images were broken.

The current gitattributes setting

```
* text=auto
```

will change CRLF in jpgs and pngs to LF – and thus break the image.

Please add lines to serve images as binary.

That will save other people some hours of headscratching ;-)

**Comment by LukeAskew** [comment]
Do you have a recommendation to what the gittatributes file should look like? Perhaps a PR?
