### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by juanfernandes** [fbrctr/fabricator#261]
Not really an issue perhaps, but maybe a lack of knowledge/documentation. 

I'm working a multi-language site and wondered if I can create a data file for each page, that has the text for each page, in 3 different languages? 

I haven't worked out how'd I'd switch the pages.

Is this possible?

**Comment by LukeAskew** [comment]
Interesting problem. I'm not entirely sure how you'd achieve this without creating duplicates of templates, which would be difficult to maintain.

This goes again the nature of Fabricator - it's not meant to be a static site generator, but of a toolkit generator. Your components and templates should be agnostic of content. "Views" are really meant to just be blueprints for how all the components can be strung together. The end system (site with real back-end) is where you'd pipe in the content.
