### ISSUE TITLE
Strange inconsistency/bug with Front Matter data in materials context

### ISSUE THREAD

**Issue by iamkeir** [fbrctr/fabricator#262]
Hey there,

I am encountering some odd behaviour as follows...

I have the following snippet of Front matter, HTML and handlebars:

```

---
day: tuesday
actors:
  - arnie
  - claude
shopping:
  fruit: apple
  amount: 20

---
What day is it? {{ day }}<br />
Action film stars: {{ actors}}<br />
Action film stars: {{#each actors}}{{this}}{{/each}}<br />
Items to purchase: {{ shopping }}<br />
Fruit: {{ shopping.fruit }}<br />
Shopping: {{#each shopping}}{{.}}{{/each}}<br />
```

In any _views_ page, it plays out as expected:

```
What day is it? tuesday
Action film stars: arnie,claude
Action film stars: arnieclaude
Items to purchase: [object Object]
Fruit: apple
Shopping: apple20
```

However, in any _materials_, some of the data is output, but the array stuff is... inconsistent:

```
What day is it? tuesday
Action film stars: arnie,claude
Action film stars: 
Items to purchase: [object Object]
Fruit: 
Shopping:
```

Any ideas what could be causing this?

**Comment by LukeAskew** [comment]
Not sure what's going on here. I can investigate, but I've been pretty short on time, so I can't promise a speedy fix.

**Comment by orangehaze** [comment]
@LukeAskew, any insight from investigating this issue? @iamkeir, were you ever able to find a workaround?

**Comment by iamkeir** [comment]
@orangehaze afraid not, just had to avoid the usage. I've moved over to other pattern library frameworks, such as http://patternlab.io/
