### ISSUE TITLE
How to add scss / js files example

### ISSUE THREAD

**Issue by Webtransformer** [fbrctr/fabricator#267]
I am sorry, I read all the documentation and tried the gulp way but I still failed. Can someone please give me examples how to add additional scss and js files without concatenation. I want all files separate?

In "src" folder I added a scss and js folder with some files in it. I added gulps task for them but they seem to be ignored.
Example 1:
"src/scss/styles.scss"

Example 2:
"src/js/custom.js"

Which files I have to edit so that the destination files are created automatically?

**Comment by james-dowell** [comment]
I've done something similar to this in the past with stylesheets. I needed to split some of my stylesheets for alternate purposes.

If it helps, I altered the config object in the gulpfile to hold an array of scss files like so:

```
...
		styles: {
			fabricator: 'src/assets/fabricator/styles/fabricator.scss',
			toolkit: [
				'src/assets/toolkit/styles/toolkit.scss',
				'src/assets/toolkit/styles/tools.scss',
				'src/assets/toolkit/styles/shared.scss',
				'src/assets/toolkit/styles/oldie.scss'
			]
		},
...
```

Gulp should be able to handle that without making any other changes to the file. This reads from 4 separate files in the `src/assets/toolkit/styles` folder and outputs `toolkit.css`, `tools.css`, `shared.css`, `oldie.css` in the dist folder.

As for the JS I think you might want to play around with the webpack config in the `webpack.config.js` 

Hope that helps :)

**Comment by Webtransformer** [comment]
Thanks! It worked :-)

Did some research and now running a gulp task for copying the js files:

`// Copy JS Files to Distribution
gulp.task('copyJSFiles', function() {
   gulp.src('src/assets/js/**/*.js').pipe(gulp.dest('dist/assets/js/'));
});

// default build task
gulp.task('default', ['clean'], function () {

	// define build tasks
	var tasks = [
		'styles',
		'scripts',
		'images',
		'assemble',
        'copyJSFiles',
	];

	// run build
	runSequence(tasks, function () {
		if (config.dev) {
			gulp.start('serve');
		}
	});

});
`

**Comment by james-dowell** [comment]
No problem, glad to help :)

That will work as long as your only using ES5 JavaScript. If you want to be using the nice ES6 syntax with babel you'll need to get Webpack to do that bit for you.

I might have a play later on today and I'll post any findings here incase you want to use it in the future.
