### ISSUE TITLE
Using Fabricator with existing site

### ISSUE THREAD

**Issue by wguldin** [fbrctr/fabricator#270]
Hi, 

I'm looking at various style guide solutions for our web app, which is growing. I looked around a fair bit, but can't seem to find any documentation for setting up a fabricator instance for an already established project.

What's the best way to do this? Would I need a seperate repo for the styleguide, or can I simply scope it to a folder in my project?

**Comment by LukeAskew** [comment]
This will be tough. Fabricator is really designed to help with the initial development.

If your existing site already has a build system for the styles and scripts you could remove those portions of the gulpfile and just use the templating task to generate your documentation site.

You'll need to modify the `default` layout to point to your already compiled stylesheet and javascript files, then add your `.html` materials as needed.

**Comment by wguldin** [comment]
Ah, I see, well thank you for the response. I really like fabricator's flexibility, it'd be cool if you could figure out a good workflow for existing projects. I think a lot of people, even with established design systems, are looking for something like this.
