### ISSUE TITLE
Menu and data source

### ISSUE THREAD

**Issue by danmv** [fbrctr/fabricator#274]
Can anyone give me an example or walk me through the steps on how I can order my navigation sections and subsections in a specific order? 

I would like to have my navigation be like this: 
- Overview 
1. Setup 
2. Download 
- Basics  
1. Colors 
2. Typography
- Components 
- Patterns 
- Examples 
- Docs

How do it setup up the f-menu.html to read from the  toolkit.yml or do I need to create a f-menu.yml?

**Comment by LukeAskew** [comment]
I do this often with toolkits. You'll need to modify the f-menu hbs template to read from `data.toolkit` (if you prefer defining data in that format).

You could also just hard-code your menu items.
