### ISSUE TITLE
Prettify HTML

### ISSUE THREAD

**Issue by hubertinio** [fbrctr/fabricator#279]
Is there any way to prettify HTML output?
Thanks in advance

**Comment by Sensiblemnd** [comment]
Could you be more specific with what you mean by prettify?

**Comment by hubertinio** [comment]
Yes, I can. Something for format an ugly HTML code, making it readable and pretty, with the proper indentation, without line ending spaces, on space between HTML attributes and etc.

#html-beautifier

**Comment by Sensiblemnd** [comment]
What code editor do you use?

**Comment by hubertinio** [comment]
Rather Netbeans, but Im backend developer. I want get prettify HTML from frontend department for all my team (many editors).

**Comment by hubertinio** [comment]
In pretty HTML is simpler compare code between what we have in backend and new changes.

**Comment by LeBenLeBen** [comment]
Fabricator already beautify the HTML output with [js-beautify](https://www.npmjs.com/package/js-beautify). I’m not sure I get your issue either.
