### ISSUE TITLE
White space not being removed

### ISSUE THREAD

**Issue by kaydwithers** [fbrctr/fabricator#280]
For some reason Fabricator is ignoring white space. 

i.e for inline-block elements. Adding a comment should remove white space but it does not work in Fabricator.

```
<ul>
    <li>Tab 1</li><!--

 --><li>Tab 2</li>
</ul>
```

Does anyone know what might be wrong? Any help would be greatly appreciated.

**Comment by LeBenLeBen** [comment]
[Fabricator-assemble](https://github.com/fbrctr/fabricator-assemble) use an [HTML parser](https://www.npmjs.com/package/js-beautify#css--html) which "beautify" it. It is probably responsible for adding extra spaces here.
