### ISSUE TITLE
Fabricator build error whenever PNG image is added to src/assets/toolkit/images

### ISSUE THREAD

**Issue by silviali** [fbrctr/fabricator#285]
Other formats of image have no problem going through the build.  But every time an PNG image is added to the src, the build breaks.  Any idea how to fix this?

the error it shows is:
`events.js:160`
      `throw er; // Unhandled 'error' event`
      `^`
`Error: The system cannot find the path specified.`

`at notFoundError (C:\Projects\ISG Fabricator\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:11:11)`

`at verifyENOENT (C:\Projects\ISG Fabricator\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:46:16)`

`at ChildProcess.cp.emit (C:\Projects\ISG Fabricator\node_modules\execa\node_modules\cross-spawn\lib\enoent.js:33:19)`

`at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)`

Once the PNG is removed, the build runs smooth as butter.  But I have images that i need to put in Fabricator that are PNG.  Can't avoid using them.

**Comment by LukeAskew** [comment]
Sounds like a error with your dependency resolution. You may try reinstalling/upgrading your packages.

I also recommend using the Yarn package manager over npm.
