### ISSUE TITLE
Implement Vuejs

### ISSUE THREAD

**Issue by niho28** [fbrctr/fabricator#289]
Hello

While I have managed to implement Vuejs in a very basic way (CDN) has anyone managed to implement vue js properly with fabricator without simply dumping a cdn into the toolkit?

Thanks

**Comment by LukeAskew** [comment]
Sorry, I don't have any experience with Vue + Fabricator.

Closing because it falls out of the scope of this project, but others are welcome to contribute to an answer.

**Comment by berkandirim** [comment]
I'm trying to use Vue with Fabricator. My problem is that Fabricator treats {{ }} as handlebars and strips, but I need it for my Vue data. Any suggestions?

**Comment by niho28** [comment]
To output your vue data trying esacping with \ 

For example \{{ item.title }}

**Comment by berkandirim** [comment]
@niho28 thanks a lot!
