### ISSUE TITLE
Showing different or no markup for each item, rather than just duplicating that markup.

### ISSUE THREAD

**Issue by BeauKelsey** [fbrctr/fabricator#290]
I know this sounds weird. I want to be able to have separate control over the item preview and the item code. 

Say I have "button.html", the item code get's escaped because I am referencing this whole button.html file with {{{material @key @root}}}. **How can I place the below code in my button material html file and achieve the expected results?** 

I also thought about having a separate html file for item previews and item code but that seems like it could get out hand.

```html
<div class="f-item-preview">
    <button class="lfy-button">Take a payment</button>
</div>

<div class="f-item-code f-item-hidden" data-f-toggle="code">
    <pre><code class="language-markup">
    <button class="lfy-button">Take a payment</button>
    </code></pre>
</div> 
```

**Comment by LukeAskew** [comment]
You could define a property in your front-matter and change the material rendering to use that property rather than the "material" code.

I think something like this would work:

```
---
preview: |
  <SomeThing
    foo={'bar'}
  />
---

<div class="something">
  ...
</div>

```

**Comment by BeauKelsey** [comment]
Excellent! I’ll try it! Thank you!
