### ISSUE TITLE
Won't compile/start on AWS

### ISSUE THREAD

**Issue by xopj** [fbrctr/fabricator#308]
I setup a clean new AWS micro ECS and ended up getting an error when trying to run; npm start

I'm able to run it locally on a mac and another ubuntu environment, seems like it's Amazon Linux related maybe? I tested these same version numbers for node/npm on ubuntu and they work so I know the older versions are stable. 

npm-debug.log copied below:

`

- 0 info it worked if it ends with ok
- 1 verbose cli [ '/home/ec2-user/.nvm/versions/node/v6.11.2/bin/node',
- 1 verbose cli   '/home/ec2-user/.nvm/versions/node/v6.11.2/bin/npm',
- 1 verbose cli   'start' ]
- 2 info using npm@3.10.10
- 3 info using node@v6.11.2
- 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
- 5 info lifecycle fabricator@1.3.1~prestart: fabricator@1.3.1
- 6 verbose lifecycle fabricator@1.3.1~prestart: unsafe-perm in lifecycle true
- 7 verbose lifecycle fabricator@1.3.1~prestart: PATH: /home/ec2-user/.nvm/versions/node/v6.11.2/lib/node_modules/npm/bin/node-gyp-bin:/home/ec2-user/environment/test/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v6.11.2/bin:/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/gems/ruby-2.4.1@global/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/bin:/usr/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/usr/local/rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin
- 8 verbose lifecycle fabricator@1.3.1~prestart: CWD: /home/ec2-user/environment/test
- 9 silly lifecycle fabricator@1.3.1~prestart: Args: [ '-c', 'npm install' ]
- 10 silly lifecycle fabricator@1.3.1~prestart: Returned: code: 0  signal: null
- 11 info lifecycle fabricator@1.3.1~start: fabricator@1.3.1
- 12 verbose lifecycle fabricator@1.3.1~start: unsafe-perm in lifecycle true
- 13 verbose lifecycle fabricator@1.3.1~start: PATH: /home/ec2-user/.nvm/versions/node/v6.11.2/lib/node_modules/npm/bin/node-gyp-bin:/home/ec2-user/environment/test/node_modules/.bin:/home/ec2-user/.nvm/versions/node/v6.11.2/bin:/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/gems/ruby-2.4.1@global/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/usr/local/bin:/bin:/usr/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/usr/local/rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin
- 14 verbose lifecycle fabricator@1.3.1~start: CWD: /home/ec2-user/environment/test
- 15 silly lifecycle fabricator@1.3.1~start: Args: [ '-c', 'gulp --dev' ]
- 16 silly lifecycle fabricator@1.3.1~start: Returned: code: 1  signal: null
- 17 info lifecycle fabricator@1.3.1~start: Failed to exec start script
- 18 verbose stack Error: fabricator@1.3.1 start: `gulp --dev`
- 18 verbose stack Exit status 1
- 18 verbose stack     at EventEmitter.<anonymous> (/home/ec2-user/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
- 18 verbose stack     at emitTwo (events.js:106:13)
- 18 verbose stack     at EventEmitter.emit (events.js:191:7)
- 18 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v6.11.2/lib/node_modules/npm/lib/utils/spawn.js:40:14)
- 18 verbose stack     at emitTwo (events.js:106:13)
- 18 verbose stack     at ChildProcess.emit (events.js:191:7)
- 18 verbose stack     at maybeClose (internal/child_process.js:891:16)
- 18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
- 19 verbose pkgid fabricator@1.3.1
- 20 verbose cwd /home/ec2-user/environment/test
- 21 error Linux 4.9.51-10.52.amzn1.x86_64
- 22 error argv "/home/ec2-user/.nvm/versions/node/v6.11.2/bin/node" "/home/ec2-user/.nvm/versions/node/v6.11.2/bin/npm" "start"
- 23 error node v6.11.2
- 24 error npm  v3.10.10
- 25 error code ELIFECYCLE
- 26 error fabricator@1.3.1 start: `gulp --dev`
- 26 error Exit status 1
- 27 error Failed at the fabricator@1.3.1 start script 'gulp --dev'.
- 27 error Make sure you have the latest version of node.js and npm installed.
- 27 error If you do, this is most likely a problem with the fabricator package,
- 27 error not with npm itself.
- 27 error Tell the author that this fails on your system:
- 27 error     gulp --dev
- 27 error You can get information on how to open an issue for this project with:
- 27 error     npm bugs fabricator
- 27 error Or if that isn't available, you can get their info via:
- 27 error     npm owner ls fabricator
- 27 error There is likely additional logging output above.
- 28 verbose exit [ 1, true ]

`

**Comment by mavame** [comment]
This could be permissions related, but it isn’t an issue with the library.
