### ISSUE TITLE
Hash Tag for Finding changes (and possibly auto replacing)

### ISSUE THREAD

**Issue by mrbinky3000** [fbrctr/fabricator#51]
I would like Fabricator to automatically append a data attribute to the outermost element in a component and/or structure.  Call the attribute something like data-fab (make the attribute a configurable option) and set the value to a short hash value representing the contents of the component or structure.  ( Example of short hash id's:  http://www.hashids.org/ )

For example, the HTML for a button...

```
<a href="#" class="button">Click Me</a>
```
... becomes ...
```
<a href="#" class="button" data-fab="9r7CESj">
```
When someone edits this button in the future.  Fabricator can search a specified directory (or array of directories, globs, etc) for all occurrences of the old hash value and notify you of all the files and lines in the directory that need to be updated.

Optionally, if the current component is EXACTLY the same (configurable option for ignoring whitespace), it can just go ahead and swap out the old for the new safely.

So the steps would be:
* Detect change to a component.
* Search a folder for all instances of the hash
* Update if it can do so safely.
* In addition, generate some sort of report detailing all the files and line numbers where that hash was found.  Make note of the spots that were automatically updated.

**Comment by LukeAskew** [comment]
Closed due to lack of demand.

**Comment by qaidj** [comment]
@mrbinky3000 - although this wont be officially supported with Fab, did you find a way to satisfy the needs that inspired this issue?
