### ISSUE TITLE
How to configure gulp.js to get images to show

### ISSUE THREAD

**Issue by qaid** [fbrctr/fabricator#59]
I'm feeling daft again.

I see that the gulp file points the `images` task to `src(config.src.images)`. In my file, the value of `config.src.images` was originally `'./src/toolkit/assets/img/**/*'`.

I do have such a directory set up, but I am not getting the images to render. 

Any hints on what I might be doing wrong here?

**Comment by haydenhancock** [comment]
Sorry to open this thread back up but I can't seem to get the images to work either. I've tried everything mentioned here. I've created a folder in src/toolkit/assets/images and placed my images there. I have not been able to get them to display properly. Any suggestion on what I am doing wrong?

**Comment by LukeAskew** [comment]
are you seeing errors?

**Comment by haydenhancock** [comment]
When I run npm run I do not see any errors.

**Comment by dietergeerts** [comment]
I also had this problem, with no error given. After some investigation, I noticed the imagemin function did it. I commented it out in my project and all was working fine. I don't know the exact problem, still need to check out.
```
// images
gulp.task('images', ['favicon'], function () {
	return gulp.src(config.src.images)
		//.pipe(imagemin()) // This is causing issues with images!!! TODO: Check this!
		.pipe(gulp.dest(config.dest + '/toolkit/images'));
});
```

**Comment by LukeAskew** [comment]
I can't reproduce this issue. I just started with a clean instance from master and it worked.

Are images dumping out to the `dist` folder? That is the webroot so reference files accordingly.

```
<img src="toolkit/images/chicken.jpg" alt="">
```

**Comment by haydenhancock** [comment]
Luke, thanks for your reply. I am not 100% sure why it wasn't building the images folder, however, I recreated it and it seems to be working as expected.
