### ISSUE TITLE
Ability to change text of component

### ISSUE THREAD

**Issue by adamweis** [fbrctr/fabricator#69]
In some cases, I think it would be helpful to have the ability to change the text used in a specific component.

This would increase the reusability of components across more structures and templates, and would help to increase the level of fidelity of these higher-level elements.

**Comment by etoxin** [comment]
+1 just spent 30 mins trying to figure out how to do this.

**Comment by LukeAskew** [comment]
This is now part of [v1.0.0](https://github.com/fbrctr/fabricator/releases/tag/v1.0.0)

http://fbrctr.github.io/building-a-toolkit/data.html

**Comment by Yago** [comment]
Maybe I can help a bit.

For example, you have a button as the most basic of your component and you want to include it in your form material, but without the same label. You can do something like : 

**button.html**
```html
<button class="btn btn-primary">
  {{#if label}}
    {{label}}
  {{^}}
    My primary button
  {{/if}}
</button>
```

**form.html**
```html
...
{{> buttons label='Submit my form !' }}
...
```

Maybe I don't really understand how we can use the data, but this solution works also pretty well :wink:
