### ISSUE TITLE
Component html source files

### ISSUE THREAD

**Issue by kflorence** [fbrctr/fabricator#81]
I would like my components to be stored in template files, like Handlebars for example, so that they are more portable for use outside of the styleguide without having to copy/paste and modify html. I'm thinking, perhaps, that the easiest way to integrate that into the current fabricator system would be to put them somewhere else and compile them into html files that live in the components directory.

Have you guys put any thought into doing something like this? If not, I will start tinkering. :)

**Comment by LukeAskew** [comment]
@kflorence Check out the enhancements to the way partials are done. #102 on the "better-partials" branch.

Let me know if this meets your needs or what you think could be improved.

**Comment by kflorence** [comment]
@LukeAskew Hey there, I actually ended up rolling my own since I couldn't find anything that suited my requirements. You can see it here: https://github.com/solarmosaic/styleguide

It was done as a hackathon project at my current company, so it's still a bit messy but we will be cleaning it up soon.

I'll be on vacation for the next week, but I'll try to play around with the new branch when I get some free time.

**Comment by LukeAskew** [comment]
Closing in favor of new templating engine in [v1.0.0](https://github.com/fbrctr/fabricator/releases/tag/v1.0.0)
