### ISSUE TITLE
Make sidebar collapsable

### ISSUE THREAD

**Issue by LukeAskew** [fbrctr/fabricator#82]
The sidebar can throw-off the breakpoints for your toolkit. Add the ability to collapse the sidebar to make developing in the documentation site more useful.

Currently, you have to develop components/structures in a template to get an accurate picture of how they will look/function.

**Comment by Spone** [comment]
Hi there,
in addition to this, it could be useful to have a way to render each component and structure on its own page. This way you can test them on a mobile device, or load them in a resizable iframe (as [Pattern Lab](http://demo.patternlab.io/?p=molecules-media-block) does, using [ish.](https://github.com/bradfrost/ish.)).
What do you think?

**Comment by LukeAskew** [comment]
Yeah that's a great call out. I've had the need/desire to isolate components for more focused development. Currently, there's no easy way to do this outside of a "template". 

I'm not positive a dedicated page is the best way to handle this, but isolation is a need. I'll think about some ways to achieve this. Thanks for echoing this need.

**Comment by LukeAskew** [comment]
This is now part of [v1.0.0](https://github.com/fbrctr/fabricator/releases/tag/v1.0.0)
