### ISSUE TITLE
How does 'notes' work?

### ISSUE THREAD

**Issue by ctdesign** [fbrctr/fabricator#88]
I'm confused as to how the notes feature should work - is this intended to allow us to add notes per component?

**Comment by csergiuu** [comment]
Hello guys, I just have another question about this. 

I've created .md file but it seems to ignore things I've got on .html file. 
Any advice?

Thanks!
Cheers

**Comment by cgray24** [comment]
same here.  the .md files seem to take precedence and its content is used as the material content, not as notes. Anyone else solve this? Feel at some point it must have been broken with an update.

**Comment by DavidDronsfield** [comment]
Same :( The html file isn't showing. Just the .md content.
