### ISSUE TITLE
Grouping/Ordering Components?

### ISSUE THREAD

**Issue by dietergeerts** [fbrctr/fabricator#94]
Hi, Is there an easy way to group and/or order components? When working on a large application with many components, the list gets way too long and it's hard to browse. Can this be added?

**Comment by haydenhancock** [comment]
Ordering components would be a huge benefit. I guess I could come up with some naming convention that would order it for me though. As @dietergeerts mentioned, I will need more time to determine a better solution.

**Comment by LukeAskew** [comment]
Heads up - I am working a rewrite of the templating task that will allow for stuff like this. Hoping to have it ready for review later this week.

**Comment by haydenhancock** [comment]
Cool. Would definitely be interesting in seeing what you come up with!

**Comment by kennethillman** [comment]
Hi @LukeAskew , is magic templating task ready for review? 

Will it handle inclusions of subfolders?

Like if i want to group html files in different folder within "STRUCTURES" and it all still compiles to the dist/toolkit/structures.html file.  

src folder ex.

- STRUCTURES
- - form.html
- - SUBFOLDER1
- - - subfolder1.html
- - SUBFOLDER2
- - - subfolder2.html

**Comment by LukeAskew** [comment]
It's not ready yet - haven't had time to commit recently, though its still in the works.

A feature of the rewrite will be the ability to organize things in more than just two buckets (components and structures). You'll be able to define your own taxonomy. For instance, you might want something like:

```
├── components
├── forms
└── typography
```

I think the flexibility to organize with subfolders is a good idea, but you might not need it if you have the ability to define your own top-level categories of UI.

But I like flexibility, so I can try to include it :smile:

**Comment by kennethillman** [comment]
The rewrite feature sounds great and thanks for the quick reply.
Hope you can fix the sub folder inclusion, i really need it :)

**Comment by LukeAskew** [comment]
@kennethillman Rewrite is ready to checkout. It's on the `better-partials` branch.

Check it out #102

**Comment by LukeAskew** [comment]
Shoot. Just realized you've been there done that. Thanks for the input! :guitar:

**Comment by LukeAskew** [comment]
This is now part of [v1.0.0](https://github.com/fbrctr/fabricator/releases/tag/v1.0.0)
